# Generated by Django 3.1.3 on 2021-02-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(verbose_name='いいね')),
                ('comments', models.IntegerField(verbose_name='コメント数')),
                ('count', models.IntegerField(verbose_name='投稿数')),
                ('label', models.CharField(max_length=100, verbose_name='投稿日')),
            ],
        ),
    ]
