# Generated by Django 3.1.3 on 2021-02-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='ハッシュタグ')),
                ('count', models.IntegerField(verbose_name='投稿数')),
                ('label', models.CharField(max_length=100, verbose_name='投稿日')),
            ],
        ),
    ]
